version: '3.8'
services:
  smf:
    container_name: mail-forwarder
    image: zixia/simple-mail-forwarder
    restart: always
    ports:
      - "25:25"
    environment:
      - SMF_CONFIG=info@on-it.design:dor.yashar@gmail.com
      #;box2@on-it.design:mybox@gmail.com;box1@domain2.com:mybox@gmail.com
    volumes:
      - /opt/projects/mail_forwarder/volumes/logs:/var/log/postfix